In [1]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [2]:
# 1. Define your connection credentials
USER = "root"
PASSWORD = "Abhi8383055393"
HOST = "localhost"  # or an IP address
PORT = "3306"  # default MySQL port
DATABASE = "ecommmerce_analysis"

In [3]:
# 2. Create the connection string (Connection URL)
# Format: mysql+pymysql://user:password@host:port/database
connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

In [4]:
# 3. Create the SQLAlchemy engine
engine = create_engine(connection_string)

In [5]:
employees = pd.read_csv('C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/python_data/practice/enterprise ecommerce project/data/employees.csv')

In [6]:
employees.head()

,employee_id,employee_name,gender,age,designation,department,region,hire_date,salary,manager_id
0,EMP0031,Dalaja Gupta,Female,37,Sales Manager,Analytics,West,2022-09-27,699318.0,EMP0010
1,EMP0173,Max Dada,Female,23,Regional Manager,Operations,East,2025-03-10,409888.0,EMP0010
2,EMP0085,Aarna Kala,Female,33,Business Analyst,Sales,East,2025-01-01,1095038.0,EMP0003
3,EMP0200,Nimrat Char,NaN,42,Sales Executive,Supply Chain,West,2025-02-03,1502506.0,EMP0008
4,EMP0061,Dalbir Sule,Male,60,Warehouse Manager,Analytics,East,2017-08-24,957829.0,EMP0001

In [7]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    210 non-null    object
 1   employee_name  210 non-null    object
 2   gender         202 non-null    object
 3   age            210 non-null    int64
 4   designation    210 non-null    object
 5   department     203 non-null    object
 6   region         210 non-null    object
 7   hire_date      210 non-null    object
 8   salary         199 non-null    float64
 9   manager_id     200 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 16.5+ KB

In [8]:
employees = employees.drop_duplicates(subset='employee_id')

In [9]:
employees['employee_name'] = employees['employee_name'].str.strip().str.title()

In [10]:
employees = employees.dropna(subset='gender')

In [11]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, 0 to 209
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    192 non-null    object
 1   employee_name  192 non-null    object
 2   gender         192 non-null    object
 3   age            192 non-null    int64
 4   designation    192 non-null    object
 5   department     186 non-null    object
 6   region         192 non-null    object
 7   hire_date      192 non-null    object
 8   salary         183 non-null    float64
 9   manager_id     182 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 16.5+ KB

In [12]:
employees[employees['department'].isna() == True]

,employee_id,employee_name,gender,age,designation,department,region,hire_date,salary,manager_id
12,EMP0171,Vedhika Acharya,Male,39,Inventory Analyst,NaN,South,2022-02-06,1432913.0,EMP0003
38,EMP0083,Teerth Borde,Female,43,Data Analyst,NaN,South,2023-08-07,1280188.0,EMP0001
40,EMP0198,Liam Chauhan,Female,49,Senior Sales Executive,NaN,South,2021-02-03,1097352.0,EMP0001
56,EMP0140,Jacob Dalal,Female,28,Sales Executive,NaN,North,2025-10-04,1402999.0,EMP0003
75,EMP0052,Ikshita Dixit,Male,29,Business Analyst,NaN,South,2023-11-27,1444185.0,EMP0009
130,EMP0041,Lekha Rau,Male,26,Operations Executive,NaN,North,2017-04-24,NaN,EMP0002

In [13]:
# getting the map
designation_map = (
    employees.dropna(subset=['designation', 'department'])
    .drop_duplicates(subset='designation')
    .set_index('designation')['department']
)

In [14]:
employees['department'] = employees['department'].fillna(employees['designation'].map(designation_map))

In [15]:
employees['department'].isna().value_counts()

department
False    192
Name: count, dtype: int64

In [16]:
employees['hire_date'] = pd.to_datetime(employees['hire_date'] , format='ISO8601', errors='coerce')

In [17]:
employees['hire_date'].value_counts()

hire_date
2031-05-01    5
2025-10-04    2
2017-04-24    2
2025-10-21    2
2016-07-19    2
             ..
2025-07-26    1
2020-10-28    1
2017-05-25    1
2017-12-01    1
2020-12-21    1
Name: count, Length: 184, dtype: int64

In [18]:
# age outliers
employees = employees[employees['age'] <= 120]

In [19]:
# salary outliers
employees = employees[employees['salary'] > 0]

In [20]:
# Feature engineering:

# Salary Band
# Employee Tenure

In [21]:
# Years of Experience
employees['years_of_experience'] = (
    (pd.Timestamp.today() - employees['hire_date']).dt.days / 365.25
).astype(int)

In [22]:
employees['years_of_experience']

0      3
1      1
2      1
4      8
5      5
      ..
204    7
205    0
206    5
207    9
208    8
Name: years_of_experience, Length: 174, dtype: int64

In [23]:
employees['salary']

0       699318.0
1       409888.0
2      1095038.0
4       957829.0
5       668343.0
         ...
204     758943.0
205     875272.0
206    1525965.0
207     326533.0
208    1201922.0
Name: salary, Length: 174, dtype: float64

In [24]:
# salary band means set the high low status to them 
employees['salary_band'] = pd.qcut(
    employees['salary'],
    q=4,
    labels=['Low','Medium','High','Very High']
)

In [25]:
employees['salary_band'].value_counts()

salary_band
Low          44
Very High    44
Medium       43
High         43
Name: count, dtype: int64

In [26]:
# calculate employees tenure
today = pd.Timestamp.today().normalize()

In [27]:
employees['employee_tenure'] = (
    (today - employees['hire_date']).dt.days // 365
)

In [28]:
employees['employee_tenure']

0      3
1      1
2      1
4      8
5      5
      ..
204    7
205    0
206    5
207    9
208    8
Name: employee_tenure, Length: 174, dtype: int64

In [29]:
# # SQL 
# Easy
# Count employees by department.
# Average salary by designation.
# Employees by region.
# Medium
# Top 5 highest-paid employees.
# Average salary by department.
# Employees with missing salaries.
# Duplicate employee records.
# Advanced
# Rank employees by salary within each department.
# Find employees earning above their department average.
# Count employees reporting to each manager.
# Calculate salary contribution by region.

In [30]:
conn = sqlite3.connect('managing.db')

In [31]:
employees.to_sql('employees', conn, if_exists='replace',index=False)

174

In [32]:
employees.to_sql("employees",engine,if_exists='replace',index=False)

174

In [33]:
pd.read_sql_query('select * from employees limit 3',conn)

,employee_id,employee_name,gender,age,designation,department,region,hire_date,salary,manager_id,years_of_experience,salary_band,employee_tenure
0,EMP0031,Dalaja Gupta,Female,37,Sales Manager,Analytics,West,2022-09-27 00:00:00,699318.0,EMP0010,3,Low,3
1,EMP0173,Max Dada,Female,23,Regional Manager,Operations,East,2025-03-10 00:00:00,409888.0,EMP0010,1,Low,1
2,EMP0085,Aarna Kala,Female,33,Business Analyst,Sales,East,2025-01-01 00:00:00,1095038.0,EMP0003,1,High,1

In [34]:
employees.to_csv("C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/python_data/practice/enterprise ecommerce project/data/employees.csv" , index=False)